version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
      - 28017:28017

  backend:
    build: ./backend/.
    container_name: backend
    ports:
      - 8000:3333
    restart: always
    depends_on:
      - mongodb
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/mydb
      - PORT=3333
